services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - .:/app
    command: sh -c "python3 -B -m app.main"
    ports:
      - "8000:8000"
      - "8080:8080"
