services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - .:/app
    command: sh -c "python3 -B -m app.main"
    ports:
      - "8000:8000"
      - "8080:8080"

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: ${P_DB}
      POSTGRES_USER: ${P_USER}
      POSTGRES_PASSWORD: ${P_PASS}
    ports:
      - "5432:5432"
