"""remove author

Revision ID: e427ae16f9d4
Revises: 6d7781c525f0
Create Date: 2024-10-19 14:22:25.948241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e427ae16f9d4"
down_revision: Union[str, None] = "6d7781c525f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("book_author_id_fkey", "book", type_="foreignkey")
    op.drop_table("author")
    op.add_column("book", sa.Column("author", sa.String(), nullable=False))
    op.drop_column("book", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "book_author_id_fkey", "book", "author", ["author_id"], ["id"]
    )
    op.drop_column("book", "author")
    op.create_table(
        "author",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="author_pkey"),
        sa.UniqueConstraint("name", name="author_name_key"),
    )
    # ### end Alembic commands ###
